# This build should never run as CI or against a pull request.
name: $(BuildDefinitionName)_$(date:yyMM).$(date:dd)$(rev:rrr)
trigger: none
pr: none

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

parameters:
  - name: buildConfigurations
    type: object
    default:
      - Release
  - name: buildPlatforms
    type: object
    default:
      - x64
      - arm64
  - name: versionNumber
    type: string
    default: '0.0.1'

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    customBuildTags:
    - 1ES.PT.ViaStartRight
    pool:
      name: SHINE-INT-S
      image: SHINE-VS17-Latest
      os: windows

    stages:
    - stage: build
      displayName: Build (Complete)
      pool:
        name: SHINE-INT-L
        image: SHINE-VS17-Latest
        os: windows
      jobs:
      - job: Build
        strategy:
          matrix:
            ${{ each config in parameters.buildConfigurations }}:
              ${{ each platform in parameters.buildPlatforms }}:
                ${{ config }}_${{ platform }}:
                  BuildConfiguration: ${{ config }}
                  BuildPlatform: ${{ platform }}
        templateContext:
          outputs:
          - output: pipelineArtifact
            artifactName: setup-$(BuildPlatform)
            targetPath: $(Build.ArtifactStagingDirectory)
          sdl:
            baseline:
              baselineFile: $(Build.SourcesDirectory)\.pipelines\sdl.gdnbaselines
        displayName: Build
        timeoutInMinutes: 240 # Some of the 1ES Pipeline stuff and Loc take a very long time
        cancelTimeoutInMinutes: 1
        variables:
          NUGET_RESTORE_MSBUILD_ARGS: /p:Platform=$(BuildPlatform) # Required for nuget to work due to self contained
          NODE_OPTIONS: --max_old_space_size=16384
          IsPipeline: 1 # The installer uses this to detect whether it should pick up localizations
          SkipCppCodeAnalysis: 1 # Skip the code analysis to speed up release CI. It runs on PR CI, anyway
          IsExperimentationLive: 1 # The build and installer use this to turn on experimentation
        steps:
        - checkout: self
          clean: true
          submodules: true
          persistCredentials: True

        # Publishing the GPO files
        - task: 1ES.PublishPipelineArtifact@1
          displayName: 'Publish Artifact: GPO Files'
          inputs:
            targetPath: src\gpo\assets
            artifactName: GroupPolicyObjectsFiles-${{ parameters.versionNumber }}
